openapi: 3.0.2
info:
  title: TIPT REST Web services
  description: TIPT Web services to perform Call Transfer
  version: 3.1.3
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CallTransferRequest:
      type: object
      properties:
        destination:
          type: object
          properties:
            address:
              type: string
            userId:
              type: string
            queueId:
              type: string
        attributes:
          type: object
          additionalProperties: true
        externalContactId:
          type: string
        correlationId:
          type: string
    CallTransferRequestResponse:
      type: object
      properties:
        success:
          type: boolean
        code:
          type: integer
          format: int32
        message:
          type: string
security:
  - basicAuth: []
paths:
  /v1/transferCall:
    post:
      description: The API to request TIPT to transfer the call
      operationId: transferCall
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallTransferRequest'
        required: true
      responses:
        '200':
          description: Returns transfer call status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallTransferRequestResponse'
        default:
          description: error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallTransferRequestResponse'
